export const labelsDetails = {
  benefitId: 'N° de prestacion',
  lotNumber: 'N° de lote',
  benefitType: 'Tipo',
  certificateNumber: 'N° Certificado',
  applicationDate: 'Fecha de solicitud',
  portfolio: 'Cartera',
  plan: 'Plan',
  signatureAmount: 'Monto Firma',
  duesQuantity: 'Cantidad de cuotas',
  duesAmount: 'Monto de la cuota',
  amountGranted: 'Monto Otorgado',
  observations: 'Observaciones',
  benefitStatus: 'Estado de la prestación',
  commercializer: 'Comercializador',
  grantedPeriod: 'Periodo otorgado',
  proceedingGranted: 'Legajo entregado',
  statusDate: 'Fecha Estado',
};

export const labelsRepartitions = {
  repartition: 'Repartición',
  distributionCode: 'Código',
  dependence: 'Dependencia',
  fileNumber: 'N° Legajo',
  fileItem: 'Item Legajo',
  paymentMethod: 'Forma de cobro',
  paymentMethodRecovery: 'Forma de Cobro Recupero',
  bankName: 'Banco',
  cbu: 'CBU',
  bankBranchName: 'Sucursal bancaria',
  bankAccountNumber: 'N° de cuenta',
  programCode: 'Código de programa',
  sequenceNumber: 'N° de secuencia',
};

export const labelsPartners = {
  partnerId: 'numero de socio',
  name: 'Nombre',
  lastName: 'Apellido',
  admissionDate: 'Fecha de ingreso',
  documentType: 'Tipo de Documento',
  documentNumber: 'N de documento',
  gender: 'Genero',
  cuil: 'N de CUIL',
  civilState: 'Estado Civil',
  status: 'Estado',
  email: 'Email',
};
